SELECT ?pl ?tl ?p2l ?ol WHERE {
<http://dbpedia.org/resource/Fugazi> a <http://dbpedia.org/ontology/Band> ; ?p ?t . 
?t ?p2 ?o .
?p rdfs:label ?pl .
?t rdfs:label ?tl .
?p2 rdfs:label ?p2l .
?o a <http://dbpedia.org/ontology/Band> .
?o rdfs:label ?ol .

FILTER (
(langMatches(lang(?ol), "en") || lang(?ol) = "" ) && 
(langMatches(lang(?pl), "en") || lang(?pl) = "" ) &&
(langMatches(lang(?tl), "en") || lang(?tl) = "" ) &&
(langMatches(lang(?p2l), "en") || lang(?p2l) = "" )
)
}
